// Code generated by ogen, DO NOT EDIT.

package go_payu

// CustomersCustomerIdGetParams is parameters of GET /customers/{customerId} operation.
type CustomersCustomerIdGetParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	CustomerId     string
}

// CustomersCustomerIdPaymentMethodsTokenPostParams is parameters of POST /customers/{customerId}/payment-methods/{token} operation.
type CustomersCustomerIdPaymentMethodsTokenPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	CustomerId     string
	Token          string
}

// CustomersPostParams is parameters of POST /customers operation.
type CustomersPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
}

// PaymentsPaymentidAuthorizationsPostParams is parameters of POST /payments/{paymentid}/authorizations operation.
type PaymentsPaymentidAuthorizationsPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	Paymentid      string
}

// PaymentsPaymentidCapturesPostParams is parameters of POST /payments/{paymentid}/captures operation.
type PaymentsPaymentidCapturesPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	Paymentid      string
}

// PaymentsPaymentidChargesPostParams is parameters of POST /payments/{paymentid}/charges operation.
type PaymentsPaymentidChargesPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	Paymentid      string
}

// PaymentsPaymentidCreditsPostParams is parameters of POST /payments/{paymentid}/credits operation.
type PaymentsPaymentidCreditsPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	Paymentid      string
}

// PaymentsPaymentidRefundsPostParams is parameters of POST /payments/{paymentid}/refunds operation.
type PaymentsPaymentidRefundsPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	Paymentid      string
}

// PaymentsPaymentidVoidsPostParams is parameters of POST /payments/{paymentid}/voids operation.
type PaymentsPaymentidVoidsPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
	Paymentid      string
}

// PaymentsPostParams is parameters of POST /payments operation.
type PaymentsPostParams struct {
	AppID          OptString
	PrivateKey     OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
	IdempotencyKey OptString
}

// TokensPostParams is parameters of POST /tokens operation.
type TokensPostParams struct {
	AppID          OptString
	PublicKey      OptString
	APIVersion     OptString
	XPaymentsOsEnv OptString
}
