// Code generated by ogen, DO NOT EDIT.

package go_payu

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/BillingAddress
type BillingAddress struct {
	Country string `json:"country"`
	State   string `json:"state"`
	City    string `json:"city"`
	Line1   string `json:"line1"`
}

// GetCountry returns the value of Country.
func (s *BillingAddress) GetCountry() string {
	return s.Country
}

// GetState returns the value of State.
func (s *BillingAddress) GetState() string {
	return s.State
}

// GetCity returns the value of City.
func (s *BillingAddress) GetCity() string {
	return s.City
}

// GetLine1 returns the value of Line1.
func (s *BillingAddress) GetLine1() string {
	return s.Line1
}

// SetCountry sets the value of Country.
func (s *BillingAddress) SetCountry(val string) {
	s.Country = val
}

// SetState sets the value of State.
func (s *BillingAddress) SetState(val string) {
	s.State = val
}

// SetCity sets the value of City.
func (s *BillingAddress) SetCity(val string) {
	s.City = val
}

// SetLine1 sets the value of Line1.
func (s *BillingAddress) SetLine1(val string) {
	s.Line1 = val
}

// Ref: #/components/schemas/CustomerCreateSuccessResponse
type CustomerCreateSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of customer creation.
	Created OptString `json:"created"`
	// Timestamp of customer modification.
	Modified          OptString `json:"modified"`
	CustomerReference OptString `json:"customer_reference"`
	// Customer email address.
	Email OptString `json:"email"`
}

// GetID returns the value of ID.
func (s *CustomerCreateSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *CustomerCreateSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetModified returns the value of Modified.
func (s *CustomerCreateSuccessResponse) GetModified() OptString {
	return s.Modified
}

// GetCustomerReference returns the value of CustomerReference.
func (s *CustomerCreateSuccessResponse) GetCustomerReference() OptString {
	return s.CustomerReference
}

// GetEmail returns the value of Email.
func (s *CustomerCreateSuccessResponse) GetEmail() OptString {
	return s.Email
}

// SetID sets the value of ID.
func (s *CustomerCreateSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *CustomerCreateSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetModified sets the value of Modified.
func (s *CustomerCreateSuccessResponse) SetModified(val OptString) {
	s.Modified = val
}

// SetCustomerReference sets the value of CustomerReference.
func (s *CustomerCreateSuccessResponse) SetCustomerReference(val OptString) {
	s.CustomerReference = val
}

// SetEmail sets the value of Email.
func (s *CustomerCreateSuccessResponse) SetEmail(val OptString) {
	s.Email = val
}

// Ref: #/components/schemas/CustomerGetSuccessResponse
type CustomerGetSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of customer creation.
	Created OptString `json:"created"`
	// Timestamp of customer modification.
	Modified          OptString `json:"modified"`
	CustomerReference OptString `json:"customer_reference"`
	// Customer email address.
	Email          OptString       `json:"email"`
	PaymentMethods []PaymentMethod `json:"payment_methods"`
}

// GetID returns the value of ID.
func (s *CustomerGetSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *CustomerGetSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetModified returns the value of Modified.
func (s *CustomerGetSuccessResponse) GetModified() OptString {
	return s.Modified
}

// GetCustomerReference returns the value of CustomerReference.
func (s *CustomerGetSuccessResponse) GetCustomerReference() OptString {
	return s.CustomerReference
}

// GetEmail returns the value of Email.
func (s *CustomerGetSuccessResponse) GetEmail() OptString {
	return s.Email
}

// GetPaymentMethods returns the value of PaymentMethods.
func (s *CustomerGetSuccessResponse) GetPaymentMethods() []PaymentMethod {
	return s.PaymentMethods
}

// SetID sets the value of ID.
func (s *CustomerGetSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *CustomerGetSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetModified sets the value of Modified.
func (s *CustomerGetSuccessResponse) SetModified(val OptString) {
	s.Modified = val
}

// SetCustomerReference sets the value of CustomerReference.
func (s *CustomerGetSuccessResponse) SetCustomerReference(val OptString) {
	s.CustomerReference = val
}

// SetEmail sets the value of Email.
func (s *CustomerGetSuccessResponse) SetEmail(val OptString) {
	s.Email = val
}

// SetPaymentMethods sets the value of PaymentMethods.
func (s *CustomerGetSuccessResponse) SetPaymentMethods(val []PaymentMethod) {
	s.PaymentMethods = val
}

// Ref: #/components/schemas/CustomerStoreTokenSuccessResponse
type CustomerStoreTokenSuccessResponse struct {
	Type               OptString         `json:"type"`
	Token              OptString         `json:"token"`
	TokenType          OptTokenType      `json:"token_type"`
	Fingerprint        OptString         `json:"fingerprint"`
	State              OptString         `json:"state"`
	HolderName         OptString         `json:"holder_name"`
	ExpirationDate     OptString         `json:"expiration_date"`
	Last4Digits        OptString         `json:"last_4_digits"`
	PassLuhnValidation OptBool           `json:"pass_luhn_validation"`
	BinNumber          OptString         `json:"bin_number"`
	Vendor             OptString         `json:"vendor"`
	Issuer             OptString         `json:"issuer"`
	CardType           OptString         `json:"card_type"`
	Level              OptString         `json:"level"`
	CountryCode        OptString         `json:"country_code"`
	Created            OptString         `json:"created"`
	BillingAddress     OptBillingAddress `json:"billing_address"`
	Href               OptString         `json:"href"`
	// Link to the customer.
	Customer OptString `json:"customer"`
}

// GetType returns the value of Type.
func (s *CustomerStoreTokenSuccessResponse) GetType() OptString {
	return s.Type
}

// GetToken returns the value of Token.
func (s *CustomerStoreTokenSuccessResponse) GetToken() OptString {
	return s.Token
}

// GetTokenType returns the value of TokenType.
func (s *CustomerStoreTokenSuccessResponse) GetTokenType() OptTokenType {
	return s.TokenType
}

// GetFingerprint returns the value of Fingerprint.
func (s *CustomerStoreTokenSuccessResponse) GetFingerprint() OptString {
	return s.Fingerprint
}

// GetState returns the value of State.
func (s *CustomerStoreTokenSuccessResponse) GetState() OptString {
	return s.State
}

// GetHolderName returns the value of HolderName.
func (s *CustomerStoreTokenSuccessResponse) GetHolderName() OptString {
	return s.HolderName
}

// GetExpirationDate returns the value of ExpirationDate.
func (s *CustomerStoreTokenSuccessResponse) GetExpirationDate() OptString {
	return s.ExpirationDate
}

// GetLast4Digits returns the value of Last4Digits.
func (s *CustomerStoreTokenSuccessResponse) GetLast4Digits() OptString {
	return s.Last4Digits
}

// GetPassLuhnValidation returns the value of PassLuhnValidation.
func (s *CustomerStoreTokenSuccessResponse) GetPassLuhnValidation() OptBool {
	return s.PassLuhnValidation
}

// GetBinNumber returns the value of BinNumber.
func (s *CustomerStoreTokenSuccessResponse) GetBinNumber() OptString {
	return s.BinNumber
}

// GetVendor returns the value of Vendor.
func (s *CustomerStoreTokenSuccessResponse) GetVendor() OptString {
	return s.Vendor
}

// GetIssuer returns the value of Issuer.
func (s *CustomerStoreTokenSuccessResponse) GetIssuer() OptString {
	return s.Issuer
}

// GetCardType returns the value of CardType.
func (s *CustomerStoreTokenSuccessResponse) GetCardType() OptString {
	return s.CardType
}

// GetLevel returns the value of Level.
func (s *CustomerStoreTokenSuccessResponse) GetLevel() OptString {
	return s.Level
}

// GetCountryCode returns the value of CountryCode.
func (s *CustomerStoreTokenSuccessResponse) GetCountryCode() OptString {
	return s.CountryCode
}

// GetCreated returns the value of Created.
func (s *CustomerStoreTokenSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetBillingAddress returns the value of BillingAddress.
func (s *CustomerStoreTokenSuccessResponse) GetBillingAddress() OptBillingAddress {
	return s.BillingAddress
}

// GetHref returns the value of Href.
func (s *CustomerStoreTokenSuccessResponse) GetHref() OptString {
	return s.Href
}

// GetCustomer returns the value of Customer.
func (s *CustomerStoreTokenSuccessResponse) GetCustomer() OptString {
	return s.Customer
}

// SetType sets the value of Type.
func (s *CustomerStoreTokenSuccessResponse) SetType(val OptString) {
	s.Type = val
}

// SetToken sets the value of Token.
func (s *CustomerStoreTokenSuccessResponse) SetToken(val OptString) {
	s.Token = val
}

// SetTokenType sets the value of TokenType.
func (s *CustomerStoreTokenSuccessResponse) SetTokenType(val OptTokenType) {
	s.TokenType = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *CustomerStoreTokenSuccessResponse) SetFingerprint(val OptString) {
	s.Fingerprint = val
}

// SetState sets the value of State.
func (s *CustomerStoreTokenSuccessResponse) SetState(val OptString) {
	s.State = val
}

// SetHolderName sets the value of HolderName.
func (s *CustomerStoreTokenSuccessResponse) SetHolderName(val OptString) {
	s.HolderName = val
}

// SetExpirationDate sets the value of ExpirationDate.
func (s *CustomerStoreTokenSuccessResponse) SetExpirationDate(val OptString) {
	s.ExpirationDate = val
}

// SetLast4Digits sets the value of Last4Digits.
func (s *CustomerStoreTokenSuccessResponse) SetLast4Digits(val OptString) {
	s.Last4Digits = val
}

// SetPassLuhnValidation sets the value of PassLuhnValidation.
func (s *CustomerStoreTokenSuccessResponse) SetPassLuhnValidation(val OptBool) {
	s.PassLuhnValidation = val
}

// SetBinNumber sets the value of BinNumber.
func (s *CustomerStoreTokenSuccessResponse) SetBinNumber(val OptString) {
	s.BinNumber = val
}

// SetVendor sets the value of Vendor.
func (s *CustomerStoreTokenSuccessResponse) SetVendor(val OptString) {
	s.Vendor = val
}

// SetIssuer sets the value of Issuer.
func (s *CustomerStoreTokenSuccessResponse) SetIssuer(val OptString) {
	s.Issuer = val
}

// SetCardType sets the value of CardType.
func (s *CustomerStoreTokenSuccessResponse) SetCardType(val OptString) {
	s.CardType = val
}

// SetLevel sets the value of Level.
func (s *CustomerStoreTokenSuccessResponse) SetLevel(val OptString) {
	s.Level = val
}

// SetCountryCode sets the value of CountryCode.
func (s *CustomerStoreTokenSuccessResponse) SetCountryCode(val OptString) {
	s.CountryCode = val
}

// SetCreated sets the value of Created.
func (s *CustomerStoreTokenSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetBillingAddress sets the value of BillingAddress.
func (s *CustomerStoreTokenSuccessResponse) SetBillingAddress(val OptBillingAddress) {
	s.BillingAddress = val
}

// SetHref sets the value of Href.
func (s *CustomerStoreTokenSuccessResponse) SetHref(val OptString) {
	s.Href = val
}

// SetCustomer sets the value of Customer.
func (s *CustomerStoreTokenSuccessResponse) SetCustomer(val OptString) {
	s.Customer = val
}

type CustomersCustomerIdPaymentMethodsTokenPostReq struct{}

type CustomersPostReq struct{}

type ErrorResponse struct {
	MoreInfo    OptString `json:"more_info"`
	Category    OptString `json:"category"`
	Description OptString `json:"description"`
}

// GetMoreInfo returns the value of MoreInfo.
func (s *ErrorResponse) GetMoreInfo() OptString {
	return s.MoreInfo
}

// GetCategory returns the value of Category.
func (s *ErrorResponse) GetCategory() OptString {
	return s.Category
}

// GetDescription returns the value of Description.
func (s *ErrorResponse) GetDescription() OptString {
	return s.Description
}

// SetMoreInfo sets the value of MoreInfo.
func (s *ErrorResponse) SetMoreInfo(val OptString) {
	s.MoreInfo = val
}

// SetCategory sets the value of Category.
func (s *ErrorResponse) SetCategory(val OptString) {
	s.Category = val
}

// SetDescription sets the value of Description.
func (s *ErrorResponse) SetDescription(val OptString) {
	s.Description = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/NextAction
type NextAction struct {
	// Possible action name.
	Action string `json:"action"`
	// Link to run current action.
	Href string `json:"href"`
}

// GetAction returns the value of Action.
func (s *NextAction) GetAction() string {
	return s.Action
}

// GetHref returns the value of Href.
func (s *NextAction) GetHref() string {
	return s.Href
}

// SetAction sets the value of Action.
func (s *NextAction) SetAction(val string) {
	s.Action = val
}

// SetHref sets the value of Href.
func (s *NextAction) SetHref(val string) {
	s.Href = val
}

// NewOptBillingAddress returns new OptBillingAddress with value set to v.
func NewOptBillingAddress(v BillingAddress) OptBillingAddress {
	return OptBillingAddress{
		Value: v,
		Set:   true,
	}
}

// OptBillingAddress is optional BillingAddress.
type OptBillingAddress struct {
	Value BillingAddress
	Set   bool
}

// IsSet returns true if OptBillingAddress was set.
func (o OptBillingAddress) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBillingAddress) Reset() {
	var v BillingAddress
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBillingAddress) SetTo(v BillingAddress) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBillingAddress) Get() (v BillingAddress, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBillingAddress) Or(d BillingAddress) BillingAddress {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentAuthSuccessResponseProviderSpecificData returns new OptPaymentAuthSuccessResponseProviderSpecificData with value set to v.
func NewOptPaymentAuthSuccessResponseProviderSpecificData(v PaymentAuthSuccessResponseProviderSpecificData) OptPaymentAuthSuccessResponseProviderSpecificData {
	return OptPaymentAuthSuccessResponseProviderSpecificData{
		Value: v,
		Set:   true,
	}
}

// OptPaymentAuthSuccessResponseProviderSpecificData is optional PaymentAuthSuccessResponseProviderSpecificData.
type OptPaymentAuthSuccessResponseProviderSpecificData struct {
	Value PaymentAuthSuccessResponseProviderSpecificData
	Set   bool
}

// IsSet returns true if OptPaymentAuthSuccessResponseProviderSpecificData was set.
func (o OptPaymentAuthSuccessResponseProviderSpecificData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentAuthSuccessResponseProviderSpecificData) Reset() {
	var v PaymentAuthSuccessResponseProviderSpecificData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentAuthSuccessResponseProviderSpecificData) SetTo(v PaymentAuthSuccessResponseProviderSpecificData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentAuthSuccessResponseProviderSpecificData) Get() (v PaymentAuthSuccessResponseProviderSpecificData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentAuthSuccessResponseProviderSpecificData) Or(d PaymentAuthSuccessResponseProviderSpecificData) PaymentAuthSuccessResponseProviderSpecificData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentAuthSuccessResponseResult returns new OptPaymentAuthSuccessResponseResult with value set to v.
func NewOptPaymentAuthSuccessResponseResult(v PaymentAuthSuccessResponseResult) OptPaymentAuthSuccessResponseResult {
	return OptPaymentAuthSuccessResponseResult{
		Value: v,
		Set:   true,
	}
}

// OptPaymentAuthSuccessResponseResult is optional PaymentAuthSuccessResponseResult.
type OptPaymentAuthSuccessResponseResult struct {
	Value PaymentAuthSuccessResponseResult
	Set   bool
}

// IsSet returns true if OptPaymentAuthSuccessResponseResult was set.
func (o OptPaymentAuthSuccessResponseResult) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentAuthSuccessResponseResult) Reset() {
	var v PaymentAuthSuccessResponseResult
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentAuthSuccessResponseResult) SetTo(v PaymentAuthSuccessResponseResult) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentAuthSuccessResponseResult) Get() (v PaymentAuthSuccessResponseResult, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentAuthSuccessResponseResult) Or(d PaymentAuthSuccessResponseResult) PaymentAuthSuccessResponseResult {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentCapturesSuccessResponseResult returns new OptPaymentCapturesSuccessResponseResult with value set to v.
func NewOptPaymentCapturesSuccessResponseResult(v PaymentCapturesSuccessResponseResult) OptPaymentCapturesSuccessResponseResult {
	return OptPaymentCapturesSuccessResponseResult{
		Value: v,
		Set:   true,
	}
}

// OptPaymentCapturesSuccessResponseResult is optional PaymentCapturesSuccessResponseResult.
type OptPaymentCapturesSuccessResponseResult struct {
	Value PaymentCapturesSuccessResponseResult
	Set   bool
}

// IsSet returns true if OptPaymentCapturesSuccessResponseResult was set.
func (o OptPaymentCapturesSuccessResponseResult) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentCapturesSuccessResponseResult) Reset() {
	var v PaymentCapturesSuccessResponseResult
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentCapturesSuccessResponseResult) SetTo(v PaymentCapturesSuccessResponseResult) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentCapturesSuccessResponseResult) Get() (v PaymentCapturesSuccessResponseResult, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentCapturesSuccessResponseResult) Or(d PaymentCapturesSuccessResponseResult) PaymentCapturesSuccessResponseResult {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentChargesSuccessResponseProviderSpecificData returns new OptPaymentChargesSuccessResponseProviderSpecificData with value set to v.
func NewOptPaymentChargesSuccessResponseProviderSpecificData(v PaymentChargesSuccessResponseProviderSpecificData) OptPaymentChargesSuccessResponseProviderSpecificData {
	return OptPaymentChargesSuccessResponseProviderSpecificData{
		Value: v,
		Set:   true,
	}
}

// OptPaymentChargesSuccessResponseProviderSpecificData is optional PaymentChargesSuccessResponseProviderSpecificData.
type OptPaymentChargesSuccessResponseProviderSpecificData struct {
	Value PaymentChargesSuccessResponseProviderSpecificData
	Set   bool
}

// IsSet returns true if OptPaymentChargesSuccessResponseProviderSpecificData was set.
func (o OptPaymentChargesSuccessResponseProviderSpecificData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentChargesSuccessResponseProviderSpecificData) Reset() {
	var v PaymentChargesSuccessResponseProviderSpecificData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentChargesSuccessResponseProviderSpecificData) SetTo(v PaymentChargesSuccessResponseProviderSpecificData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentChargesSuccessResponseProviderSpecificData) Get() (v PaymentChargesSuccessResponseProviderSpecificData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentChargesSuccessResponseProviderSpecificData) Or(d PaymentChargesSuccessResponseProviderSpecificData) PaymentChargesSuccessResponseProviderSpecificData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentChargesSuccessResponseResult returns new OptPaymentChargesSuccessResponseResult with value set to v.
func NewOptPaymentChargesSuccessResponseResult(v PaymentChargesSuccessResponseResult) OptPaymentChargesSuccessResponseResult {
	return OptPaymentChargesSuccessResponseResult{
		Value: v,
		Set:   true,
	}
}

// OptPaymentChargesSuccessResponseResult is optional PaymentChargesSuccessResponseResult.
type OptPaymentChargesSuccessResponseResult struct {
	Value PaymentChargesSuccessResponseResult
	Set   bool
}

// IsSet returns true if OptPaymentChargesSuccessResponseResult was set.
func (o OptPaymentChargesSuccessResponseResult) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentChargesSuccessResponseResult) Reset() {
	var v PaymentChargesSuccessResponseResult
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentChargesSuccessResponseResult) SetTo(v PaymentChargesSuccessResponseResult) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentChargesSuccessResponseResult) Get() (v PaymentChargesSuccessResponseResult, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentChargesSuccessResponseResult) Or(d PaymentChargesSuccessResponseResult) PaymentChargesSuccessResponseResult {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentCreditsSuccessResponseProviderSpecificData returns new OptPaymentCreditsSuccessResponseProviderSpecificData with value set to v.
func NewOptPaymentCreditsSuccessResponseProviderSpecificData(v PaymentCreditsSuccessResponseProviderSpecificData) OptPaymentCreditsSuccessResponseProviderSpecificData {
	return OptPaymentCreditsSuccessResponseProviderSpecificData{
		Value: v,
		Set:   true,
	}
}

// OptPaymentCreditsSuccessResponseProviderSpecificData is optional PaymentCreditsSuccessResponseProviderSpecificData.
type OptPaymentCreditsSuccessResponseProviderSpecificData struct {
	Value PaymentCreditsSuccessResponseProviderSpecificData
	Set   bool
}

// IsSet returns true if OptPaymentCreditsSuccessResponseProviderSpecificData was set.
func (o OptPaymentCreditsSuccessResponseProviderSpecificData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentCreditsSuccessResponseProviderSpecificData) Reset() {
	var v PaymentCreditsSuccessResponseProviderSpecificData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentCreditsSuccessResponseProviderSpecificData) SetTo(v PaymentCreditsSuccessResponseProviderSpecificData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentCreditsSuccessResponseProviderSpecificData) Get() (v PaymentCreditsSuccessResponseProviderSpecificData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentCreditsSuccessResponseProviderSpecificData) Or(d PaymentCreditsSuccessResponseProviderSpecificData) PaymentCreditsSuccessResponseProviderSpecificData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentCreditsSuccessResponseResult returns new OptPaymentCreditsSuccessResponseResult with value set to v.
func NewOptPaymentCreditsSuccessResponseResult(v PaymentCreditsSuccessResponseResult) OptPaymentCreditsSuccessResponseResult {
	return OptPaymentCreditsSuccessResponseResult{
		Value: v,
		Set:   true,
	}
}

// OptPaymentCreditsSuccessResponseResult is optional PaymentCreditsSuccessResponseResult.
type OptPaymentCreditsSuccessResponseResult struct {
	Value PaymentCreditsSuccessResponseResult
	Set   bool
}

// IsSet returns true if OptPaymentCreditsSuccessResponseResult was set.
func (o OptPaymentCreditsSuccessResponseResult) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentCreditsSuccessResponseResult) Reset() {
	var v PaymentCreditsSuccessResponseResult
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentCreditsSuccessResponseResult) SetTo(v PaymentCreditsSuccessResponseResult) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentCreditsSuccessResponseResult) Get() (v PaymentCreditsSuccessResponseResult, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentCreditsSuccessResponseResult) Or(d PaymentCreditsSuccessResponseResult) PaymentCreditsSuccessResponseResult {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentRefundsSuccessResponseResult returns new OptPaymentRefundsSuccessResponseResult with value set to v.
func NewOptPaymentRefundsSuccessResponseResult(v PaymentRefundsSuccessResponseResult) OptPaymentRefundsSuccessResponseResult {
	return OptPaymentRefundsSuccessResponseResult{
		Value: v,
		Set:   true,
	}
}

// OptPaymentRefundsSuccessResponseResult is optional PaymentRefundsSuccessResponseResult.
type OptPaymentRefundsSuccessResponseResult struct {
	Value PaymentRefundsSuccessResponseResult
	Set   bool
}

// IsSet returns true if OptPaymentRefundsSuccessResponseResult was set.
func (o OptPaymentRefundsSuccessResponseResult) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentRefundsSuccessResponseResult) Reset() {
	var v PaymentRefundsSuccessResponseResult
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentRefundsSuccessResponseResult) SetTo(v PaymentRefundsSuccessResponseResult) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentRefundsSuccessResponseResult) Get() (v PaymentRefundsSuccessResponseResult, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentRefundsSuccessResponseResult) Or(d PaymentRefundsSuccessResponseResult) PaymentRefundsSuccessResponseResult {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentSuccessResponseBillingAddress returns new OptPaymentSuccessResponseBillingAddress with value set to v.
func NewOptPaymentSuccessResponseBillingAddress(v PaymentSuccessResponseBillingAddress) OptPaymentSuccessResponseBillingAddress {
	return OptPaymentSuccessResponseBillingAddress{
		Value: v,
		Set:   true,
	}
}

// OptPaymentSuccessResponseBillingAddress is optional PaymentSuccessResponseBillingAddress.
type OptPaymentSuccessResponseBillingAddress struct {
	Value PaymentSuccessResponseBillingAddress
	Set   bool
}

// IsSet returns true if OptPaymentSuccessResponseBillingAddress was set.
func (o OptPaymentSuccessResponseBillingAddress) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentSuccessResponseBillingAddress) Reset() {
	var v PaymentSuccessResponseBillingAddress
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentSuccessResponseBillingAddress) SetTo(v PaymentSuccessResponseBillingAddress) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentSuccessResponseBillingAddress) Get() (v PaymentSuccessResponseBillingAddress, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentSuccessResponseBillingAddress) Or(d PaymentSuccessResponseBillingAddress) PaymentSuccessResponseBillingAddress {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentSuccessResponseOrder returns new OptPaymentSuccessResponseOrder with value set to v.
func NewOptPaymentSuccessResponseOrder(v PaymentSuccessResponseOrder) OptPaymentSuccessResponseOrder {
	return OptPaymentSuccessResponseOrder{
		Value: v,
		Set:   true,
	}
}

// OptPaymentSuccessResponseOrder is optional PaymentSuccessResponseOrder.
type OptPaymentSuccessResponseOrder struct {
	Value PaymentSuccessResponseOrder
	Set   bool
}

// IsSet returns true if OptPaymentSuccessResponseOrder was set.
func (o OptPaymentSuccessResponseOrder) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentSuccessResponseOrder) Reset() {
	var v PaymentSuccessResponseOrder
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentSuccessResponseOrder) SetTo(v PaymentSuccessResponseOrder) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentSuccessResponseOrder) Get() (v PaymentSuccessResponseOrder, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentSuccessResponseOrder) Or(d PaymentSuccessResponseOrder) PaymentSuccessResponseOrder {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentVoidsSuccessResponseProviderSpecificData returns new OptPaymentVoidsSuccessResponseProviderSpecificData with value set to v.
func NewOptPaymentVoidsSuccessResponseProviderSpecificData(v PaymentVoidsSuccessResponseProviderSpecificData) OptPaymentVoidsSuccessResponseProviderSpecificData {
	return OptPaymentVoidsSuccessResponseProviderSpecificData{
		Value: v,
		Set:   true,
	}
}

// OptPaymentVoidsSuccessResponseProviderSpecificData is optional PaymentVoidsSuccessResponseProviderSpecificData.
type OptPaymentVoidsSuccessResponseProviderSpecificData struct {
	Value PaymentVoidsSuccessResponseProviderSpecificData
	Set   bool
}

// IsSet returns true if OptPaymentVoidsSuccessResponseProviderSpecificData was set.
func (o OptPaymentVoidsSuccessResponseProviderSpecificData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentVoidsSuccessResponseProviderSpecificData) Reset() {
	var v PaymentVoidsSuccessResponseProviderSpecificData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentVoidsSuccessResponseProviderSpecificData) SetTo(v PaymentVoidsSuccessResponseProviderSpecificData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentVoidsSuccessResponseProviderSpecificData) Get() (v PaymentVoidsSuccessResponseProviderSpecificData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentVoidsSuccessResponseProviderSpecificData) Or(d PaymentVoidsSuccessResponseProviderSpecificData) PaymentVoidsSuccessResponseProviderSpecificData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentVoidsSuccessResponseResult returns new OptPaymentVoidsSuccessResponseResult with value set to v.
func NewOptPaymentVoidsSuccessResponseResult(v PaymentVoidsSuccessResponseResult) OptPaymentVoidsSuccessResponseResult {
	return OptPaymentVoidsSuccessResponseResult{
		Value: v,
		Set:   true,
	}
}

// OptPaymentVoidsSuccessResponseResult is optional PaymentVoidsSuccessResponseResult.
type OptPaymentVoidsSuccessResponseResult struct {
	Value PaymentVoidsSuccessResponseResult
	Set   bool
}

// IsSet returns true if OptPaymentVoidsSuccessResponseResult was set.
func (o OptPaymentVoidsSuccessResponseResult) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentVoidsSuccessResponseResult) Reset() {
	var v PaymentVoidsSuccessResponseResult
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentVoidsSuccessResponseResult) SetTo(v PaymentVoidsSuccessResponseResult) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentVoidsSuccessResponseResult) Get() (v PaymentVoidsSuccessResponseResult, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentVoidsSuccessResponseResult) Or(d PaymentVoidsSuccessResponseResult) PaymentVoidsSuccessResponseResult {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentsPaymentidAuthorizationsPostReq returns new OptPaymentsPaymentidAuthorizationsPostReq with value set to v.
func NewOptPaymentsPaymentidAuthorizationsPostReq(v PaymentsPaymentidAuthorizationsPostReq) OptPaymentsPaymentidAuthorizationsPostReq {
	return OptPaymentsPaymentidAuthorizationsPostReq{
		Value: v,
		Set:   true,
	}
}

// OptPaymentsPaymentidAuthorizationsPostReq is optional PaymentsPaymentidAuthorizationsPostReq.
type OptPaymentsPaymentidAuthorizationsPostReq struct {
	Value PaymentsPaymentidAuthorizationsPostReq
	Set   bool
}

// IsSet returns true if OptPaymentsPaymentidAuthorizationsPostReq was set.
func (o OptPaymentsPaymentidAuthorizationsPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentsPaymentidAuthorizationsPostReq) Reset() {
	var v PaymentsPaymentidAuthorizationsPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentsPaymentidAuthorizationsPostReq) SetTo(v PaymentsPaymentidAuthorizationsPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentsPaymentidAuthorizationsPostReq) Get() (v PaymentsPaymentidAuthorizationsPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentsPaymentidAuthorizationsPostReq) Or(d PaymentsPaymentidAuthorizationsPostReq) PaymentsPaymentidAuthorizationsPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProviderConfiguration returns new OptProviderConfiguration with value set to v.
func NewOptProviderConfiguration(v ProviderConfiguration) OptProviderConfiguration {
	return OptProviderConfiguration{
		Value: v,
		Set:   true,
	}
}

// OptProviderConfiguration is optional ProviderConfiguration.
type OptProviderConfiguration struct {
	Value ProviderConfiguration
	Set   bool
}

// IsSet returns true if OptProviderConfiguration was set.
func (o OptProviderConfiguration) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProviderConfiguration) Reset() {
	var v ProviderConfiguration
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProviderConfiguration) SetTo(v ProviderConfiguration) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProviderConfiguration) Get() (v ProviderConfiguration, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProviderConfiguration) Or(d ProviderConfiguration) ProviderConfiguration {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProviderData returns new OptProviderData with value set to v.
func NewOptProviderData(v ProviderData) OptProviderData {
	return OptProviderData{
		Value: v,
		Set:   true,
	}
}

// OptProviderData is optional ProviderData.
type OptProviderData struct {
	Value ProviderData
	Set   bool
}

// IsSet returns true if OptProviderData was set.
func (o OptProviderData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProviderData) Reset() {
	var v ProviderData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProviderData) SetTo(v ProviderData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProviderData) Get() (v ProviderData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProviderData) Or(d ProviderData) ProviderData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTokenType returns new OptTokenType with value set to v.
func NewOptTokenType(v TokenType) OptTokenType {
	return OptTokenType{
		Value: v,
		Set:   true,
	}
}

// OptTokenType is optional TokenType.
type OptTokenType struct {
	Value TokenType
	Set   bool
}

// IsSet returns true if OptTokenType was set.
func (o OptTokenType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTokenType) Reset() {
	var v TokenType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTokenType) SetTo(v TokenType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTokenType) Get() (v TokenType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTokenType) Or(d TokenType) TokenType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTokensPostReq returns new OptTokensPostReq with value set to v.
func NewOptTokensPostReq(v TokensPostReq) OptTokensPostReq {
	return OptTokensPostReq{
		Value: v,
		Set:   true,
	}
}

// OptTokensPostReq is optional TokensPostReq.
type OptTokensPostReq struct {
	Value TokensPostReq
	Set   bool
}

// IsSet returns true if OptTokensPostReq was set.
func (o OptTokensPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTokensPostReq) Reset() {
	var v TokensPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTokensPostReq) SetTo(v TokensPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTokensPostReq) Get() (v TokensPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTokensPostReq) Or(d TokensPostReq) TokensPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PaymentAuthSuccessResponse
type PaymentAuthSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of payment auth creation.
	Created               OptString                                         `json:"created"`
	ReconciliationID      OptString                                         `json:"reconciliation_id"`
	ProviderSpecificData  OptPaymentAuthSuccessResponseProviderSpecificData `json:"provider_specific_data"`
	PaymentMethod         OptPaymentMethod                                  `json:"payment_method"`
	Result                OptPaymentAuthSuccessResponseResult               `json:"result"`
	ProviderData          OptProviderData                                   `json:"provider_data"`
	Amount                OptFloat64                                        `json:"amount"`
	ProviderConfiguration OptProviderConfiguration                          `json:"provider_configuration"`
	AuthorizationType     OptString                                         `json:"authorization_type"`
}

// GetID returns the value of ID.
func (s *PaymentAuthSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *PaymentAuthSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetReconciliationID returns the value of ReconciliationID.
func (s *PaymentAuthSuccessResponse) GetReconciliationID() OptString {
	return s.ReconciliationID
}

// GetProviderSpecificData returns the value of ProviderSpecificData.
func (s *PaymentAuthSuccessResponse) GetProviderSpecificData() OptPaymentAuthSuccessResponseProviderSpecificData {
	return s.ProviderSpecificData
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaymentAuthSuccessResponse) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetResult returns the value of Result.
func (s *PaymentAuthSuccessResponse) GetResult() OptPaymentAuthSuccessResponseResult {
	return s.Result
}

// GetProviderData returns the value of ProviderData.
func (s *PaymentAuthSuccessResponse) GetProviderData() OptProviderData {
	return s.ProviderData
}

// GetAmount returns the value of Amount.
func (s *PaymentAuthSuccessResponse) GetAmount() OptFloat64 {
	return s.Amount
}

// GetProviderConfiguration returns the value of ProviderConfiguration.
func (s *PaymentAuthSuccessResponse) GetProviderConfiguration() OptProviderConfiguration {
	return s.ProviderConfiguration
}

// GetAuthorizationType returns the value of AuthorizationType.
func (s *PaymentAuthSuccessResponse) GetAuthorizationType() OptString {
	return s.AuthorizationType
}

// SetID sets the value of ID.
func (s *PaymentAuthSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *PaymentAuthSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetReconciliationID sets the value of ReconciliationID.
func (s *PaymentAuthSuccessResponse) SetReconciliationID(val OptString) {
	s.ReconciliationID = val
}

// SetProviderSpecificData sets the value of ProviderSpecificData.
func (s *PaymentAuthSuccessResponse) SetProviderSpecificData(val OptPaymentAuthSuccessResponseProviderSpecificData) {
	s.ProviderSpecificData = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaymentAuthSuccessResponse) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetResult sets the value of Result.
func (s *PaymentAuthSuccessResponse) SetResult(val OptPaymentAuthSuccessResponseResult) {
	s.Result = val
}

// SetProviderData sets the value of ProviderData.
func (s *PaymentAuthSuccessResponse) SetProviderData(val OptProviderData) {
	s.ProviderData = val
}

// SetAmount sets the value of Amount.
func (s *PaymentAuthSuccessResponse) SetAmount(val OptFloat64) {
	s.Amount = val
}

// SetProviderConfiguration sets the value of ProviderConfiguration.
func (s *PaymentAuthSuccessResponse) SetProviderConfiguration(val OptProviderConfiguration) {
	s.ProviderConfiguration = val
}

// SetAuthorizationType sets the value of AuthorizationType.
func (s *PaymentAuthSuccessResponse) SetAuthorizationType(val OptString) {
	s.AuthorizationType = val
}

type PaymentAuthSuccessResponseProviderSpecificData map[string]jx.Raw

func (s *PaymentAuthSuccessResponseProviderSpecificData) init() PaymentAuthSuccessResponseProviderSpecificData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PaymentAuthSuccessResponseResult struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PaymentAuthSuccessResponseResult) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PaymentAuthSuccessResponseResult) SetStatus(val OptString) {
	s.Status = val
}

// Ref: #/components/schemas/PaymentCapturesSuccessResponse
type PaymentCapturesSuccessResponse struct {
	ID                    OptString                               `json:"id"`
	Created               OptString                               `json:"created"`
	Result                OptPaymentCapturesSuccessResponseResult `json:"result"`
	ProviderData          OptProviderData                         `json:"provider_data"`
	Amount                OptFloat64                              `json:"amount"`
	ProviderConfiguration OptProviderConfiguration                `json:"provider_configuration"`
}

// GetID returns the value of ID.
func (s *PaymentCapturesSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *PaymentCapturesSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetResult returns the value of Result.
func (s *PaymentCapturesSuccessResponse) GetResult() OptPaymentCapturesSuccessResponseResult {
	return s.Result
}

// GetProviderData returns the value of ProviderData.
func (s *PaymentCapturesSuccessResponse) GetProviderData() OptProviderData {
	return s.ProviderData
}

// GetAmount returns the value of Amount.
func (s *PaymentCapturesSuccessResponse) GetAmount() OptFloat64 {
	return s.Amount
}

// GetProviderConfiguration returns the value of ProviderConfiguration.
func (s *PaymentCapturesSuccessResponse) GetProviderConfiguration() OptProviderConfiguration {
	return s.ProviderConfiguration
}

// SetID sets the value of ID.
func (s *PaymentCapturesSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *PaymentCapturesSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetResult sets the value of Result.
func (s *PaymentCapturesSuccessResponse) SetResult(val OptPaymentCapturesSuccessResponseResult) {
	s.Result = val
}

// SetProviderData sets the value of ProviderData.
func (s *PaymentCapturesSuccessResponse) SetProviderData(val OptProviderData) {
	s.ProviderData = val
}

// SetAmount sets the value of Amount.
func (s *PaymentCapturesSuccessResponse) SetAmount(val OptFloat64) {
	s.Amount = val
}

// SetProviderConfiguration sets the value of ProviderConfiguration.
func (s *PaymentCapturesSuccessResponse) SetProviderConfiguration(val OptProviderConfiguration) {
	s.ProviderConfiguration = val
}

type PaymentCapturesSuccessResponseResult struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PaymentCapturesSuccessResponseResult) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PaymentCapturesSuccessResponseResult) SetStatus(val OptString) {
	s.Status = val
}

// Ref: #/components/schemas/PaymentChargesSuccessResponse
type PaymentChargesSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of payment auth creation.
	Created               OptString                                            `json:"created"`
	ProviderSpecificData  OptPaymentChargesSuccessResponseProviderSpecificData `json:"provider_specific_data"`
	PaymentMethod         OptPaymentMethod                                     `json:"payment_method"`
	Result                OptPaymentChargesSuccessResponseResult               `json:"result"`
	ProviderData          OptProviderData                                      `json:"provider_data"`
	Amount                OptFloat64                                           `json:"amount"`
	ProviderConfiguration OptProviderConfiguration                             `json:"provider_configuration"`
}

// GetID returns the value of ID.
func (s *PaymentChargesSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *PaymentChargesSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetProviderSpecificData returns the value of ProviderSpecificData.
func (s *PaymentChargesSuccessResponse) GetProviderSpecificData() OptPaymentChargesSuccessResponseProviderSpecificData {
	return s.ProviderSpecificData
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaymentChargesSuccessResponse) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetResult returns the value of Result.
func (s *PaymentChargesSuccessResponse) GetResult() OptPaymentChargesSuccessResponseResult {
	return s.Result
}

// GetProviderData returns the value of ProviderData.
func (s *PaymentChargesSuccessResponse) GetProviderData() OptProviderData {
	return s.ProviderData
}

// GetAmount returns the value of Amount.
func (s *PaymentChargesSuccessResponse) GetAmount() OptFloat64 {
	return s.Amount
}

// GetProviderConfiguration returns the value of ProviderConfiguration.
func (s *PaymentChargesSuccessResponse) GetProviderConfiguration() OptProviderConfiguration {
	return s.ProviderConfiguration
}

// SetID sets the value of ID.
func (s *PaymentChargesSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *PaymentChargesSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetProviderSpecificData sets the value of ProviderSpecificData.
func (s *PaymentChargesSuccessResponse) SetProviderSpecificData(val OptPaymentChargesSuccessResponseProviderSpecificData) {
	s.ProviderSpecificData = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaymentChargesSuccessResponse) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetResult sets the value of Result.
func (s *PaymentChargesSuccessResponse) SetResult(val OptPaymentChargesSuccessResponseResult) {
	s.Result = val
}

// SetProviderData sets the value of ProviderData.
func (s *PaymentChargesSuccessResponse) SetProviderData(val OptProviderData) {
	s.ProviderData = val
}

// SetAmount sets the value of Amount.
func (s *PaymentChargesSuccessResponse) SetAmount(val OptFloat64) {
	s.Amount = val
}

// SetProviderConfiguration sets the value of ProviderConfiguration.
func (s *PaymentChargesSuccessResponse) SetProviderConfiguration(val OptProviderConfiguration) {
	s.ProviderConfiguration = val
}

type PaymentChargesSuccessResponseProviderSpecificData map[string]jx.Raw

func (s *PaymentChargesSuccessResponseProviderSpecificData) init() PaymentChargesSuccessResponseProviderSpecificData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PaymentChargesSuccessResponseResult struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PaymentChargesSuccessResponseResult) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PaymentChargesSuccessResponseResult) SetStatus(val OptString) {
	s.Status = val
}

// Ref: #/components/schemas/PaymentCreditsSuccessResponse
type PaymentCreditsSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of payment auth creation.
	Created               OptString                                            `json:"created"`
	ReconciliationID      OptString                                            `json:"reconciliation_id"`
	ProviderSpecificData  OptPaymentCreditsSuccessResponseProviderSpecificData `json:"provider_specific_data"`
	PaymentMethod         OptPaymentMethod                                     `json:"payment_method"`
	Result                OptPaymentCreditsSuccessResponseResult               `json:"result"`
	ProviderData          OptProviderData                                      `json:"provider_data"`
	Amount                OptFloat64                                           `json:"amount"`
	ProviderConfiguration OptProviderConfiguration                             `json:"provider_configuration"`
}

// GetID returns the value of ID.
func (s *PaymentCreditsSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *PaymentCreditsSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetReconciliationID returns the value of ReconciliationID.
func (s *PaymentCreditsSuccessResponse) GetReconciliationID() OptString {
	return s.ReconciliationID
}

// GetProviderSpecificData returns the value of ProviderSpecificData.
func (s *PaymentCreditsSuccessResponse) GetProviderSpecificData() OptPaymentCreditsSuccessResponseProviderSpecificData {
	return s.ProviderSpecificData
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaymentCreditsSuccessResponse) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetResult returns the value of Result.
func (s *PaymentCreditsSuccessResponse) GetResult() OptPaymentCreditsSuccessResponseResult {
	return s.Result
}

// GetProviderData returns the value of ProviderData.
func (s *PaymentCreditsSuccessResponse) GetProviderData() OptProviderData {
	return s.ProviderData
}

// GetAmount returns the value of Amount.
func (s *PaymentCreditsSuccessResponse) GetAmount() OptFloat64 {
	return s.Amount
}

// GetProviderConfiguration returns the value of ProviderConfiguration.
func (s *PaymentCreditsSuccessResponse) GetProviderConfiguration() OptProviderConfiguration {
	return s.ProviderConfiguration
}

// SetID sets the value of ID.
func (s *PaymentCreditsSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *PaymentCreditsSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetReconciliationID sets the value of ReconciliationID.
func (s *PaymentCreditsSuccessResponse) SetReconciliationID(val OptString) {
	s.ReconciliationID = val
}

// SetProviderSpecificData sets the value of ProviderSpecificData.
func (s *PaymentCreditsSuccessResponse) SetProviderSpecificData(val OptPaymentCreditsSuccessResponseProviderSpecificData) {
	s.ProviderSpecificData = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaymentCreditsSuccessResponse) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetResult sets the value of Result.
func (s *PaymentCreditsSuccessResponse) SetResult(val OptPaymentCreditsSuccessResponseResult) {
	s.Result = val
}

// SetProviderData sets the value of ProviderData.
func (s *PaymentCreditsSuccessResponse) SetProviderData(val OptProviderData) {
	s.ProviderData = val
}

// SetAmount sets the value of Amount.
func (s *PaymentCreditsSuccessResponse) SetAmount(val OptFloat64) {
	s.Amount = val
}

// SetProviderConfiguration sets the value of ProviderConfiguration.
func (s *PaymentCreditsSuccessResponse) SetProviderConfiguration(val OptProviderConfiguration) {
	s.ProviderConfiguration = val
}

type PaymentCreditsSuccessResponseProviderSpecificData map[string]jx.Raw

func (s *PaymentCreditsSuccessResponseProviderSpecificData) init() PaymentCreditsSuccessResponseProviderSpecificData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PaymentCreditsSuccessResponseResult struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PaymentCreditsSuccessResponseResult) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PaymentCreditsSuccessResponseResult) SetStatus(val OptString) {
	s.Status = val
}

// Ref: #/components/schemas/PaymentMethod
type PaymentMethod struct {
	Type               OptString         `json:"type"`
	Token              OptString         `json:"token"`
	TokenType          OptTokenType      `json:"token_type"`
	HolderName         OptString         `json:"holder_name"`
	ExpirationDate     OptString         `json:"expiration_date"`
	Last4Digits        OptString         `json:"last_4_digits"`
	PassLuhnValidation OptBool           `json:"pass_luhn_validation"`
	Fingerprint        OptString         `json:"fingerprint"`
	BinNumber          OptString         `json:"bin_number"`
	Vendor             OptString         `json:"vendor"`
	Issuer             OptString         `json:"issuer"`
	CardType           OptString         `json:"card_type"`
	Level              OptString         `json:"level"`
	CountryCode        OptString         `json:"country_code"`
	Created            OptString         `json:"created"`
	BillingAddress     OptBillingAddress `json:"billing_address"`
	Href               OptString         `json:"href"`
	Customer           OptString         `json:"customer"`
}

// GetType returns the value of Type.
func (s *PaymentMethod) GetType() OptString {
	return s.Type
}

// GetToken returns the value of Token.
func (s *PaymentMethod) GetToken() OptString {
	return s.Token
}

// GetTokenType returns the value of TokenType.
func (s *PaymentMethod) GetTokenType() OptTokenType {
	return s.TokenType
}

// GetHolderName returns the value of HolderName.
func (s *PaymentMethod) GetHolderName() OptString {
	return s.HolderName
}

// GetExpirationDate returns the value of ExpirationDate.
func (s *PaymentMethod) GetExpirationDate() OptString {
	return s.ExpirationDate
}

// GetLast4Digits returns the value of Last4Digits.
func (s *PaymentMethod) GetLast4Digits() OptString {
	return s.Last4Digits
}

// GetPassLuhnValidation returns the value of PassLuhnValidation.
func (s *PaymentMethod) GetPassLuhnValidation() OptBool {
	return s.PassLuhnValidation
}

// GetFingerprint returns the value of Fingerprint.
func (s *PaymentMethod) GetFingerprint() OptString {
	return s.Fingerprint
}

// GetBinNumber returns the value of BinNumber.
func (s *PaymentMethod) GetBinNumber() OptString {
	return s.BinNumber
}

// GetVendor returns the value of Vendor.
func (s *PaymentMethod) GetVendor() OptString {
	return s.Vendor
}

// GetIssuer returns the value of Issuer.
func (s *PaymentMethod) GetIssuer() OptString {
	return s.Issuer
}

// GetCardType returns the value of CardType.
func (s *PaymentMethod) GetCardType() OptString {
	return s.CardType
}

// GetLevel returns the value of Level.
func (s *PaymentMethod) GetLevel() OptString {
	return s.Level
}

// GetCountryCode returns the value of CountryCode.
func (s *PaymentMethod) GetCountryCode() OptString {
	return s.CountryCode
}

// GetCreated returns the value of Created.
func (s *PaymentMethod) GetCreated() OptString {
	return s.Created
}

// GetBillingAddress returns the value of BillingAddress.
func (s *PaymentMethod) GetBillingAddress() OptBillingAddress {
	return s.BillingAddress
}

// GetHref returns the value of Href.
func (s *PaymentMethod) GetHref() OptString {
	return s.Href
}

// GetCustomer returns the value of Customer.
func (s *PaymentMethod) GetCustomer() OptString {
	return s.Customer
}

// SetType sets the value of Type.
func (s *PaymentMethod) SetType(val OptString) {
	s.Type = val
}

// SetToken sets the value of Token.
func (s *PaymentMethod) SetToken(val OptString) {
	s.Token = val
}

// SetTokenType sets the value of TokenType.
func (s *PaymentMethod) SetTokenType(val OptTokenType) {
	s.TokenType = val
}

// SetHolderName sets the value of HolderName.
func (s *PaymentMethod) SetHolderName(val OptString) {
	s.HolderName = val
}

// SetExpirationDate sets the value of ExpirationDate.
func (s *PaymentMethod) SetExpirationDate(val OptString) {
	s.ExpirationDate = val
}

// SetLast4Digits sets the value of Last4Digits.
func (s *PaymentMethod) SetLast4Digits(val OptString) {
	s.Last4Digits = val
}

// SetPassLuhnValidation sets the value of PassLuhnValidation.
func (s *PaymentMethod) SetPassLuhnValidation(val OptBool) {
	s.PassLuhnValidation = val
}

// SetFingerprint sets the value of Fingerprint.
func (s *PaymentMethod) SetFingerprint(val OptString) {
	s.Fingerprint = val
}

// SetBinNumber sets the value of BinNumber.
func (s *PaymentMethod) SetBinNumber(val OptString) {
	s.BinNumber = val
}

// SetVendor sets the value of Vendor.
func (s *PaymentMethod) SetVendor(val OptString) {
	s.Vendor = val
}

// SetIssuer sets the value of Issuer.
func (s *PaymentMethod) SetIssuer(val OptString) {
	s.Issuer = val
}

// SetCardType sets the value of CardType.
func (s *PaymentMethod) SetCardType(val OptString) {
	s.CardType = val
}

// SetLevel sets the value of Level.
func (s *PaymentMethod) SetLevel(val OptString) {
	s.Level = val
}

// SetCountryCode sets the value of CountryCode.
func (s *PaymentMethod) SetCountryCode(val OptString) {
	s.CountryCode = val
}

// SetCreated sets the value of Created.
func (s *PaymentMethod) SetCreated(val OptString) {
	s.Created = val
}

// SetBillingAddress sets the value of BillingAddress.
func (s *PaymentMethod) SetBillingAddress(val OptBillingAddress) {
	s.BillingAddress = val
}

// SetHref sets the value of Href.
func (s *PaymentMethod) SetHref(val OptString) {
	s.Href = val
}

// SetCustomer sets the value of Customer.
func (s *PaymentMethod) SetCustomer(val OptString) {
	s.Customer = val
}

// Ref: #/components/schemas/PaymentRefundsSuccessResponse
type PaymentRefundsSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of payment auth creation.
	Created               OptString                              `json:"created"`
	Result                OptPaymentRefundsSuccessResponseResult `json:"result"`
	ProviderData          OptProviderData                        `json:"provider_data"`
	Amount                OptFloat64                             `json:"amount"`
	ProviderConfiguration OptProviderConfiguration               `json:"provider_configuration"`
}

// GetID returns the value of ID.
func (s *PaymentRefundsSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *PaymentRefundsSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetResult returns the value of Result.
func (s *PaymentRefundsSuccessResponse) GetResult() OptPaymentRefundsSuccessResponseResult {
	return s.Result
}

// GetProviderData returns the value of ProviderData.
func (s *PaymentRefundsSuccessResponse) GetProviderData() OptProviderData {
	return s.ProviderData
}

// GetAmount returns the value of Amount.
func (s *PaymentRefundsSuccessResponse) GetAmount() OptFloat64 {
	return s.Amount
}

// GetProviderConfiguration returns the value of ProviderConfiguration.
func (s *PaymentRefundsSuccessResponse) GetProviderConfiguration() OptProviderConfiguration {
	return s.ProviderConfiguration
}

// SetID sets the value of ID.
func (s *PaymentRefundsSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *PaymentRefundsSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetResult sets the value of Result.
func (s *PaymentRefundsSuccessResponse) SetResult(val OptPaymentRefundsSuccessResponseResult) {
	s.Result = val
}

// SetProviderData sets the value of ProviderData.
func (s *PaymentRefundsSuccessResponse) SetProviderData(val OptProviderData) {
	s.ProviderData = val
}

// SetAmount sets the value of Amount.
func (s *PaymentRefundsSuccessResponse) SetAmount(val OptFloat64) {
	s.Amount = val
}

// SetProviderConfiguration sets the value of ProviderConfiguration.
func (s *PaymentRefundsSuccessResponse) SetProviderConfiguration(val OptProviderConfiguration) {
	s.ProviderConfiguration = val
}

type PaymentRefundsSuccessResponseResult struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PaymentRefundsSuccessResponseResult) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PaymentRefundsSuccessResponseResult) SetStatus(val OptString) {
	s.Status = val
}

// Ref: #/components/schemas/PaymentSuccessResponse
type PaymentSuccessResponse struct {
	// Payment id.
	ID OptString `json:"id"`
	// Payment currency code.
	Currency OptString `json:"currency"`
	// Timestamp of payment creation.
	Created OptString `json:"created"`
	// Timestamp of payment modification.
	Modified   OptString `json:"modified"`
	IsDisputed OptBool   `json:"is_disputed"`
	// Status of the payment.
	Status              OptString                               `json:"status"`
	BillingAddress      OptPaymentSuccessResponseBillingAddress `json:"billing_address"`
	PossibleNextActions *PossibleNextActions                    `json:"possible_next_actions"`
	Order               OptPaymentSuccessResponseOrder          `json:"order"`
	// Amount to pay.
	Amount OptFloat64 `json:"amount"`
}

// GetID returns the value of ID.
func (s *PaymentSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCurrency returns the value of Currency.
func (s *PaymentSuccessResponse) GetCurrency() OptString {
	return s.Currency
}

// GetCreated returns the value of Created.
func (s *PaymentSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetModified returns the value of Modified.
func (s *PaymentSuccessResponse) GetModified() OptString {
	return s.Modified
}

// GetIsDisputed returns the value of IsDisputed.
func (s *PaymentSuccessResponse) GetIsDisputed() OptBool {
	return s.IsDisputed
}

// GetStatus returns the value of Status.
func (s *PaymentSuccessResponse) GetStatus() OptString {
	return s.Status
}

// GetBillingAddress returns the value of BillingAddress.
func (s *PaymentSuccessResponse) GetBillingAddress() OptPaymentSuccessResponseBillingAddress {
	return s.BillingAddress
}

// GetPossibleNextActions returns the value of PossibleNextActions.
func (s *PaymentSuccessResponse) GetPossibleNextActions() *PossibleNextActions {
	return s.PossibleNextActions
}

// GetOrder returns the value of Order.
func (s *PaymentSuccessResponse) GetOrder() OptPaymentSuccessResponseOrder {
	return s.Order
}

// GetAmount returns the value of Amount.
func (s *PaymentSuccessResponse) GetAmount() OptFloat64 {
	return s.Amount
}

// SetID sets the value of ID.
func (s *PaymentSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCurrency sets the value of Currency.
func (s *PaymentSuccessResponse) SetCurrency(val OptString) {
	s.Currency = val
}

// SetCreated sets the value of Created.
func (s *PaymentSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetModified sets the value of Modified.
func (s *PaymentSuccessResponse) SetModified(val OptString) {
	s.Modified = val
}

// SetIsDisputed sets the value of IsDisputed.
func (s *PaymentSuccessResponse) SetIsDisputed(val OptBool) {
	s.IsDisputed = val
}

// SetStatus sets the value of Status.
func (s *PaymentSuccessResponse) SetStatus(val OptString) {
	s.Status = val
}

// SetBillingAddress sets the value of BillingAddress.
func (s *PaymentSuccessResponse) SetBillingAddress(val OptPaymentSuccessResponseBillingAddress) {
	s.BillingAddress = val
}

// SetPossibleNextActions sets the value of PossibleNextActions.
func (s *PaymentSuccessResponse) SetPossibleNextActions(val *PossibleNextActions) {
	s.PossibleNextActions = val
}

// SetOrder sets the value of Order.
func (s *PaymentSuccessResponse) SetOrder(val OptPaymentSuccessResponseOrder) {
	s.Order = val
}

// SetAmount sets the value of Amount.
func (s *PaymentSuccessResponse) SetAmount(val OptFloat64) {
	s.Amount = val
}

type PaymentSuccessResponseBillingAddress struct {
	// Phone of the customer.
	Phone OptString `json:"phone"`
}

// GetPhone returns the value of Phone.
func (s *PaymentSuccessResponseBillingAddress) GetPhone() OptString {
	return s.Phone
}

// SetPhone sets the value of Phone.
func (s *PaymentSuccessResponseBillingAddress) SetPhone(val OptString) {
	s.Phone = val
}

type PaymentSuccessResponseOrder struct {
	ID OptString `json:"id"`
}

// GetID returns the value of ID.
func (s *PaymentSuccessResponseOrder) GetID() OptString {
	return s.ID
}

// SetID sets the value of ID.
func (s *PaymentSuccessResponseOrder) SetID(val OptString) {
	s.ID = val
}

// Ref: #/components/schemas/PaymentVoidsSuccessResponse
type PaymentVoidsSuccessResponse struct {
	// Payment ID.
	ID OptString `json:"id"`
	// Timestamp of payment auth creation.
	Created               OptString                                          `json:"created"`
	ReconciliationID      OptString                                          `json:"reconciliation_id"`
	ProviderSpecificData  OptPaymentVoidsSuccessResponseProviderSpecificData `json:"provider_specific_data"`
	Result                OptPaymentVoidsSuccessResponseResult               `json:"result"`
	ProviderData          OptProviderData                                    `json:"provider_data"`
	ProviderConfiguration OptProviderConfiguration                           `json:"provider_configuration"`
}

// GetID returns the value of ID.
func (s *PaymentVoidsSuccessResponse) GetID() OptString {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *PaymentVoidsSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetReconciliationID returns the value of ReconciliationID.
func (s *PaymentVoidsSuccessResponse) GetReconciliationID() OptString {
	return s.ReconciliationID
}

// GetProviderSpecificData returns the value of ProviderSpecificData.
func (s *PaymentVoidsSuccessResponse) GetProviderSpecificData() OptPaymentVoidsSuccessResponseProviderSpecificData {
	return s.ProviderSpecificData
}

// GetResult returns the value of Result.
func (s *PaymentVoidsSuccessResponse) GetResult() OptPaymentVoidsSuccessResponseResult {
	return s.Result
}

// GetProviderData returns the value of ProviderData.
func (s *PaymentVoidsSuccessResponse) GetProviderData() OptProviderData {
	return s.ProviderData
}

// GetProviderConfiguration returns the value of ProviderConfiguration.
func (s *PaymentVoidsSuccessResponse) GetProviderConfiguration() OptProviderConfiguration {
	return s.ProviderConfiguration
}

// SetID sets the value of ID.
func (s *PaymentVoidsSuccessResponse) SetID(val OptString) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *PaymentVoidsSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetReconciliationID sets the value of ReconciliationID.
func (s *PaymentVoidsSuccessResponse) SetReconciliationID(val OptString) {
	s.ReconciliationID = val
}

// SetProviderSpecificData sets the value of ProviderSpecificData.
func (s *PaymentVoidsSuccessResponse) SetProviderSpecificData(val OptPaymentVoidsSuccessResponseProviderSpecificData) {
	s.ProviderSpecificData = val
}

// SetResult sets the value of Result.
func (s *PaymentVoidsSuccessResponse) SetResult(val OptPaymentVoidsSuccessResponseResult) {
	s.Result = val
}

// SetProviderData sets the value of ProviderData.
func (s *PaymentVoidsSuccessResponse) SetProviderData(val OptProviderData) {
	s.ProviderData = val
}

// SetProviderConfiguration sets the value of ProviderConfiguration.
func (s *PaymentVoidsSuccessResponse) SetProviderConfiguration(val OptProviderConfiguration) {
	s.ProviderConfiguration = val
}

type PaymentVoidsSuccessResponseProviderSpecificData map[string]jx.Raw

func (s *PaymentVoidsSuccessResponseProviderSpecificData) init() PaymentVoidsSuccessResponseProviderSpecificData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PaymentVoidsSuccessResponseResult struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PaymentVoidsSuccessResponseResult) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PaymentVoidsSuccessResponseResult) SetStatus(val OptString) {
	s.Status = val
}

type PaymentsPaymentidAuthorizationsPostReq struct {
	PaymentMethod    PaymentsPaymentidAuthorizationsPostReqPaymentMethod `json:"payment_method"`
	ReconciliationID string                                              `json:"reconciliation_id"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PaymentsPaymentidAuthorizationsPostReq) GetPaymentMethod() PaymentsPaymentidAuthorizationsPostReqPaymentMethod {
	return s.PaymentMethod
}

// GetReconciliationID returns the value of ReconciliationID.
func (s *PaymentsPaymentidAuthorizationsPostReq) GetReconciliationID() string {
	return s.ReconciliationID
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PaymentsPaymentidAuthorizationsPostReq) SetPaymentMethod(val PaymentsPaymentidAuthorizationsPostReqPaymentMethod) {
	s.PaymentMethod = val
}

// SetReconciliationID sets the value of ReconciliationID.
func (s *PaymentsPaymentidAuthorizationsPostReq) SetReconciliationID(val string) {
	s.ReconciliationID = val
}

type PaymentsPaymentidAuthorizationsPostReqPaymentMethod struct {
	// Payment token.
	Token         string `json:"token"`
	Type          string `json:"type"`
	CreditCardCvv string `json:"credit_card_cvv"`
}

// GetToken returns the value of Token.
func (s *PaymentsPaymentidAuthorizationsPostReqPaymentMethod) GetToken() string {
	return s.Token
}

// GetType returns the value of Type.
func (s *PaymentsPaymentidAuthorizationsPostReqPaymentMethod) GetType() string {
	return s.Type
}

// GetCreditCardCvv returns the value of CreditCardCvv.
func (s *PaymentsPaymentidAuthorizationsPostReqPaymentMethod) GetCreditCardCvv() string {
	return s.CreditCardCvv
}

// SetToken sets the value of Token.
func (s *PaymentsPaymentidAuthorizationsPostReqPaymentMethod) SetToken(val string) {
	s.Token = val
}

// SetType sets the value of Type.
func (s *PaymentsPaymentidAuthorizationsPostReqPaymentMethod) SetType(val string) {
	s.Type = val
}

// SetCreditCardCvv sets the value of CreditCardCvv.
func (s *PaymentsPaymentidAuthorizationsPostReqPaymentMethod) SetCreditCardCvv(val string) {
	s.CreditCardCvv = val
}

type PaymentsPaymentidCapturesPostReq struct{}

type PaymentsPaymentidChargesPostReq struct{}

type PaymentsPaymentidCreditsPostReq struct{}

type PaymentsPaymentidRefundsPostReq struct{}

type PaymentsPaymentidVoidsPostReq struct{}

type PaymentsPostReq struct{}

type PossibleNextActions []NextAction

// Ref: #/components/schemas/ProviderConfiguration
type ProviderConfiguration struct {
	ID         OptString `json:"id"`
	Name       OptString `json:"name"`
	Created    OptString `json:"created"`
	Modified   OptString `json:"modified"`
	AccountID  OptString `json:"account_id"`
	ProviderID OptString `json:"provider_id"`
	Type       OptString `json:"type"`
	Href       OptString `json:"href"`
}

// GetID returns the value of ID.
func (s *ProviderConfiguration) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderConfiguration) GetName() OptString {
	return s.Name
}

// GetCreated returns the value of Created.
func (s *ProviderConfiguration) GetCreated() OptString {
	return s.Created
}

// GetModified returns the value of Modified.
func (s *ProviderConfiguration) GetModified() OptString {
	return s.Modified
}

// GetAccountID returns the value of AccountID.
func (s *ProviderConfiguration) GetAccountID() OptString {
	return s.AccountID
}

// GetProviderID returns the value of ProviderID.
func (s *ProviderConfiguration) GetProviderID() OptString {
	return s.ProviderID
}

// GetType returns the value of Type.
func (s *ProviderConfiguration) GetType() OptString {
	return s.Type
}

// GetHref returns the value of Href.
func (s *ProviderConfiguration) GetHref() OptString {
	return s.Href
}

// SetID sets the value of ID.
func (s *ProviderConfiguration) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderConfiguration) SetName(val OptString) {
	s.Name = val
}

// SetCreated sets the value of Created.
func (s *ProviderConfiguration) SetCreated(val OptString) {
	s.Created = val
}

// SetModified sets the value of Modified.
func (s *ProviderConfiguration) SetModified(val OptString) {
	s.Modified = val
}

// SetAccountID sets the value of AccountID.
func (s *ProviderConfiguration) SetAccountID(val OptString) {
	s.AccountID = val
}

// SetProviderID sets the value of ProviderID.
func (s *ProviderConfiguration) SetProviderID(val OptString) {
	s.ProviderID = val
}

// SetType sets the value of Type.
func (s *ProviderConfiguration) SetType(val OptString) {
	s.Type = val
}

// SetHref sets the value of Href.
func (s *ProviderConfiguration) SetHref(val OptString) {
	s.Href = val
}

// Ref: #/components/schemas/ProviderData
type ProviderData struct {
	ProviderName      OptString `json:"provider_name"`
	ResponseCode      OptString `json:"response_code"`
	Description       OptString `json:"description"`
	RawResponse       OptString `json:"raw_response"`
	AuthorizationCode OptString `json:"authorization_code"`
	TransactionID     OptString `json:"transaction_id"`
	ExternalID        OptString `json:"external_id"`
}

// GetProviderName returns the value of ProviderName.
func (s *ProviderData) GetProviderName() OptString {
	return s.ProviderName
}

// GetResponseCode returns the value of ResponseCode.
func (s *ProviderData) GetResponseCode() OptString {
	return s.ResponseCode
}

// GetDescription returns the value of Description.
func (s *ProviderData) GetDescription() OptString {
	return s.Description
}

// GetRawResponse returns the value of RawResponse.
func (s *ProviderData) GetRawResponse() OptString {
	return s.RawResponse
}

// GetAuthorizationCode returns the value of AuthorizationCode.
func (s *ProviderData) GetAuthorizationCode() OptString {
	return s.AuthorizationCode
}

// GetTransactionID returns the value of TransactionID.
func (s *ProviderData) GetTransactionID() OptString {
	return s.TransactionID
}

// GetExternalID returns the value of ExternalID.
func (s *ProviderData) GetExternalID() OptString {
	return s.ExternalID
}

// SetProviderName sets the value of ProviderName.
func (s *ProviderData) SetProviderName(val OptString) {
	s.ProviderName = val
}

// SetResponseCode sets the value of ResponseCode.
func (s *ProviderData) SetResponseCode(val OptString) {
	s.ResponseCode = val
}

// SetDescription sets the value of Description.
func (s *ProviderData) SetDescription(val OptString) {
	s.Description = val
}

// SetRawResponse sets the value of RawResponse.
func (s *ProviderData) SetRawResponse(val OptString) {
	s.RawResponse = val
}

// SetAuthorizationCode sets the value of AuthorizationCode.
func (s *ProviderData) SetAuthorizationCode(val OptString) {
	s.AuthorizationCode = val
}

// SetTransactionID sets the value of TransactionID.
func (s *ProviderData) SetTransactionID(val OptString) {
	s.TransactionID = val
}

// SetExternalID sets the value of ExternalID.
func (s *ProviderData) SetExternalID(val OptString) {
	s.ExternalID = val
}

// Ref: #/components/schemas/TokenSuccessResponse
type TokenSuccessResponse struct {
	// PayU Token.
	Token OptString `json:"token"`
	// Timestamp of token creation.
	Created            OptString         `json:"created"`
	PassLuhnValidation OptBool           `json:"pass_luhn_validation"`
	TokenType          OptTokenType      `json:"token_type"`
	Type               OptString         `json:"type"`
	State              OptString         `json:"state"`
	BinNumber          OptString         `json:"bin_number"`
	Vendor             OptString         `json:"vendor"`
	CardType           OptString         `json:"card_type"`
	Issuer             OptString         `json:"issuer"`
	Level              OptString         `json:"level"`
	CountryCode        OptString         `json:"country_code"`
	BillingAddress     OptBillingAddress `json:"billing_address"`
	HolderName         OptString         `json:"holder_name"`
	ExpirationDate     OptString         `json:"expiration_date"`
	Last4Digits        OptString         `json:"last_4_digits"`
	EncryptedCvv       OptString         `json:"encrypted_cvv"`
}

// GetToken returns the value of Token.
func (s *TokenSuccessResponse) GetToken() OptString {
	return s.Token
}

// GetCreated returns the value of Created.
func (s *TokenSuccessResponse) GetCreated() OptString {
	return s.Created
}

// GetPassLuhnValidation returns the value of PassLuhnValidation.
func (s *TokenSuccessResponse) GetPassLuhnValidation() OptBool {
	return s.PassLuhnValidation
}

// GetTokenType returns the value of TokenType.
func (s *TokenSuccessResponse) GetTokenType() OptTokenType {
	return s.TokenType
}

// GetType returns the value of Type.
func (s *TokenSuccessResponse) GetType() OptString {
	return s.Type
}

// GetState returns the value of State.
func (s *TokenSuccessResponse) GetState() OptString {
	return s.State
}

// GetBinNumber returns the value of BinNumber.
func (s *TokenSuccessResponse) GetBinNumber() OptString {
	return s.BinNumber
}

// GetVendor returns the value of Vendor.
func (s *TokenSuccessResponse) GetVendor() OptString {
	return s.Vendor
}

// GetCardType returns the value of CardType.
func (s *TokenSuccessResponse) GetCardType() OptString {
	return s.CardType
}

// GetIssuer returns the value of Issuer.
func (s *TokenSuccessResponse) GetIssuer() OptString {
	return s.Issuer
}

// GetLevel returns the value of Level.
func (s *TokenSuccessResponse) GetLevel() OptString {
	return s.Level
}

// GetCountryCode returns the value of CountryCode.
func (s *TokenSuccessResponse) GetCountryCode() OptString {
	return s.CountryCode
}

// GetBillingAddress returns the value of BillingAddress.
func (s *TokenSuccessResponse) GetBillingAddress() OptBillingAddress {
	return s.BillingAddress
}

// GetHolderName returns the value of HolderName.
func (s *TokenSuccessResponse) GetHolderName() OptString {
	return s.HolderName
}

// GetExpirationDate returns the value of ExpirationDate.
func (s *TokenSuccessResponse) GetExpirationDate() OptString {
	return s.ExpirationDate
}

// GetLast4Digits returns the value of Last4Digits.
func (s *TokenSuccessResponse) GetLast4Digits() OptString {
	return s.Last4Digits
}

// GetEncryptedCvv returns the value of EncryptedCvv.
func (s *TokenSuccessResponse) GetEncryptedCvv() OptString {
	return s.EncryptedCvv
}

// SetToken sets the value of Token.
func (s *TokenSuccessResponse) SetToken(val OptString) {
	s.Token = val
}

// SetCreated sets the value of Created.
func (s *TokenSuccessResponse) SetCreated(val OptString) {
	s.Created = val
}

// SetPassLuhnValidation sets the value of PassLuhnValidation.
func (s *TokenSuccessResponse) SetPassLuhnValidation(val OptBool) {
	s.PassLuhnValidation = val
}

// SetTokenType sets the value of TokenType.
func (s *TokenSuccessResponse) SetTokenType(val OptTokenType) {
	s.TokenType = val
}

// SetType sets the value of Type.
func (s *TokenSuccessResponse) SetType(val OptString) {
	s.Type = val
}

// SetState sets the value of State.
func (s *TokenSuccessResponse) SetState(val OptString) {
	s.State = val
}

// SetBinNumber sets the value of BinNumber.
func (s *TokenSuccessResponse) SetBinNumber(val OptString) {
	s.BinNumber = val
}

// SetVendor sets the value of Vendor.
func (s *TokenSuccessResponse) SetVendor(val OptString) {
	s.Vendor = val
}

// SetCardType sets the value of CardType.
func (s *TokenSuccessResponse) SetCardType(val OptString) {
	s.CardType = val
}

// SetIssuer sets the value of Issuer.
func (s *TokenSuccessResponse) SetIssuer(val OptString) {
	s.Issuer = val
}

// SetLevel sets the value of Level.
func (s *TokenSuccessResponse) SetLevel(val OptString) {
	s.Level = val
}

// SetCountryCode sets the value of CountryCode.
func (s *TokenSuccessResponse) SetCountryCode(val OptString) {
	s.CountryCode = val
}

// SetBillingAddress sets the value of BillingAddress.
func (s *TokenSuccessResponse) SetBillingAddress(val OptBillingAddress) {
	s.BillingAddress = val
}

// SetHolderName sets the value of HolderName.
func (s *TokenSuccessResponse) SetHolderName(val OptString) {
	s.HolderName = val
}

// SetExpirationDate sets the value of ExpirationDate.
func (s *TokenSuccessResponse) SetExpirationDate(val OptString) {
	s.ExpirationDate = val
}

// SetLast4Digits sets the value of Last4Digits.
func (s *TokenSuccessResponse) SetLast4Digits(val OptString) {
	s.Last4Digits = val
}

// SetEncryptedCvv sets the value of EncryptedCvv.
func (s *TokenSuccessResponse) SetEncryptedCvv(val OptString) {
	s.EncryptedCvv = val
}

// Ref: #/components/schemas/TokenType
type TokenType string

const (
	TokenTypeCreditCard          TokenType = "credit_card"
	TokenTypeCardCvvCode         TokenType = "card_cvv_code"
	TokenTypeBillingAgreement    TokenType = "billing_agreement"
	TokenTypeEncryptedCreditCard TokenType = "encrypted_credit_card"
)

// MarshalText implements encoding.TextMarshaler.
func (s TokenType) MarshalText() ([]byte, error) {
	switch s {
	case TokenTypeCreditCard:
		return []byte(s), nil
	case TokenTypeCardCvvCode:
		return []byte(s), nil
	case TokenTypeBillingAgreement:
		return []byte(s), nil
	case TokenTypeEncryptedCreditCard:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TokenType) UnmarshalText(data []byte) error {
	switch TokenType(data) {
	case TokenTypeCreditCard:
		*s = TokenTypeCreditCard
		return nil
	case TokenTypeCardCvvCode:
		*s = TokenTypeCardCvvCode
		return nil
	case TokenTypeBillingAgreement:
		*s = TokenTypeBillingAgreement
		return nil
	case TokenTypeEncryptedCreditCard:
		*s = TokenTypeEncryptedCreditCard
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TokensPostReq struct {
	TokenType      TokenType      `json:"token_type"`
	CreditCardCvv  string         `json:"credit_card_cvv"`
	CardNumber     string         `json:"card_number"`
	ExpirationDate string         `json:"expiration_date"`
	HolderName     string         `json:"holder_name"`
	BillingAddress BillingAddress `json:"billing_address"`
}

// GetTokenType returns the value of TokenType.
func (s *TokensPostReq) GetTokenType() TokenType {
	return s.TokenType
}

// GetCreditCardCvv returns the value of CreditCardCvv.
func (s *TokensPostReq) GetCreditCardCvv() string {
	return s.CreditCardCvv
}

// GetCardNumber returns the value of CardNumber.
func (s *TokensPostReq) GetCardNumber() string {
	return s.CardNumber
}

// GetExpirationDate returns the value of ExpirationDate.
func (s *TokensPostReq) GetExpirationDate() string {
	return s.ExpirationDate
}

// GetHolderName returns the value of HolderName.
func (s *TokensPostReq) GetHolderName() string {
	return s.HolderName
}

// GetBillingAddress returns the value of BillingAddress.
func (s *TokensPostReq) GetBillingAddress() BillingAddress {
	return s.BillingAddress
}

// SetTokenType sets the value of TokenType.
func (s *TokensPostReq) SetTokenType(val TokenType) {
	s.TokenType = val
}

// SetCreditCardCvv sets the value of CreditCardCvv.
func (s *TokensPostReq) SetCreditCardCvv(val string) {
	s.CreditCardCvv = val
}

// SetCardNumber sets the value of CardNumber.
func (s *TokensPostReq) SetCardNumber(val string) {
	s.CardNumber = val
}

// SetExpirationDate sets the value of ExpirationDate.
func (s *TokensPostReq) SetExpirationDate(val string) {
	s.ExpirationDate = val
}

// SetHolderName sets the value of HolderName.
func (s *TokensPostReq) SetHolderName(val string) {
	s.HolderName = val
}

// SetBillingAddress sets the value of BillingAddress.
func (s *TokensPostReq) SetBillingAddress(val BillingAddress) {
	s.BillingAddress = val
}
